name: Branch Protection Setup

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to protect"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - develop
      require_ci:
        description: "Require CI to pass"
        required: true
        default: true
        type: boolean
      require_reviews:
        description: "Require pull request reviews"
        required: true
        default: true
        type: boolean
      dismiss_stale_reviews:
        description: "Dismiss stale reviews when new commits are pushed"
        required: true
        default: true
        type: boolean

jobs:
  setup-branch-protection:
    name: Setup Branch Protection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Branch Protection
        uses: actions/github-script@v7
        with:
          script: |
            const branch = '${{ github.event.inputs.branch }}';
            const requireCI = ${{ github.event.inputs.require_ci }};
            const requireReviews = ${{ github.event.inputs.require_reviews }};
            const dismissStaleReviews = ${{ github.event.inputs.dismiss_stale_reviews }};

            const requiredStatusChecks = requireCI ? [
              'frontend-ci',
              'contracts-ci',
              'security-checks'
            ] : [];

            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branch,
                required_status_checks: {
                  strict: true,
                  contexts: requiredStatusChecks
                },
                enforce_admins: false,
                required_pull_request_reviews: requireReviews ? {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: dismissStaleReviews,
                  require_code_owner_reviews: false,
                  require_last_push_approval: false
                } : null,
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true
              });

              console.log(`✅ Branch protection rules updated for ${branch}`);
            } catch (error) {
              console.error(`❌ Failed to update branch protection for ${branch}:`, error.message);
              core.setFailed(error.message);
            }

      - name: Verify Branch Protection
        uses: actions/github-script@v7
        with:
          script: |
            const branch = '${{ github.event.inputs.branch }}';

            try {
              const protection = await github.rest.repos.getBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branch
              });

              console.log(`✅ Branch protection verified for ${branch}:`);
              console.log('- Required status checks:', protection.data.required_status_checks?.contexts || []);
              console.log('- Required reviews:', protection.data.required_pull_request_reviews ? 'enabled' : 'disabled');
              console.log('- Allow force pushes:', protection.data.allow_force_pushes);
              console.log('- Allow deletions:', protection.data.allow_deletions);
            } catch (error) {
              console.error(`❌ Failed to verify branch protection for ${branch}:`, error.message);
            }
